spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/xoj?useSSL=false&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai

  mail:
    host: ***REMOVED***
    username: ***REMOVED***

    password: ***REMOVED***
    port: 587
    default-encoding: UTF-8

  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 100

server:
  port: 8081