spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root123123
    url: jdbc:mysql://localhost:3306/oj?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=UTF-8&serverTimezone=UTC

  mail:
    host: ***REMOVED***
    username: ***REMOVED***
    password: ***REMOVED***
    port: 587
    default-encoding: UTF-8

  redis:
    port: 6379
    host: 127.0.0.1
    lettuce:
      pool:
        max-active: 100
        max-idle: 8
        min-idle: 0
        max-wait: 1000
      shutdown-timeout: 800

server:
  port: 8081
  servlet:
    session:
      timeout: 5184000

pagehelper:
  helper-dialect: mysql
  reasonable: false
  support-methods-arguments: true
  params: count=countSql

smms:
  upload-url: https://sm.ms/api/v2/upload
  delete-url: https://sm.ms/api/v2/delete/:hash
  authorization: ***REMOVED***


mailgun:
  api:
    username: xjtluoj
    password: ***REMOVED***
    base:
      url: https://api.mailgun.net/v3/xoj.codes
    messages:
      url: https://api.mailgun.net/v3/xoj.codes/messages







